version: '3.8'
services:
  api:
    build: .
    container_name: postgres-client-api
    environment:
      - DB_HOST=172.28.0.3
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=admin
      - DB_PASSWORD=adminpass
    ports:
      - "5000:5000"
    networks:
      - app-net

networks:
  app-net:
    external: true