version: '3.8'
services:
  postgres:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=sensor_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql

  client:
    build: .
    environment:
      - DB_HOST=postgres
      - DB_NAME=sensor_db
      - DB_USER=user
      - DB_PASSWORD=password
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data:
