version: '3.8'
services:
  api:
    build: .
    environment:
      - DB_HOST=local-postgres
      - DB_PORT=5432
      - DB_NAME=mydb
      - DB_USER=admin
      - DB_PASSWORD=adminpass
    ports:
      - "5000:5000"
    depends_on:
      - local-postgres
    networks:
      - app-net

networks:
  app-net:
    external: true
